{
 "title": "Spring Boot Telemetry Dashboard",
 "tags": [
  "springboot",
  "jvm",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Microservices CPU & Threads Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "JVM Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{job}} - {{state}}" }
   ]
  },
  { "title": "JVM Memory Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{job}} Used Heap"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "{{job}} Max Heap Limit"
    }
   ]
  }
 ]
}