global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ingestion-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ingestion-service:8081']

  - job_name: 'sla-engine-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sla-engine-service:8082']

  - job_name: 'alerting-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['alerting-service:8083']
